#!/bin/bash

export CLASSPATH=$CLASSPATH:`ls -1 jars/*.jar jars/worldwind/*.jar | xargs | sed "s/ /:/g"`:.
OSNAME=`uname`

if [ 'Linux' == "$OSNAME" ]; then
    DOCK=
else
    DOCK='-Xdock:icon=img/logo.png -Xdock:name=HorizonServer'
fi

RUN="java -Djava.library.path=/lib/:jars/worldwind/:jars/ -Xmx512m -Dsun.java2d.noddraw=true $DOCK org.haldean.chopper.server.ServerHost -h \"pices.dynalias.org:23\" -d"

echo $RUN

clean() {
    echo "Clean old classfiles" 1>&2
    rm org/haldean/chopper/server/*.class
    echo "Clean backup java files" 1>&2
    rm org/haldean/chopper/server/*.java\~
}

if [ 'clean' == "$1" ]; then
    clean
    exit
fi

clean

if [ 'pack' == "$1" ]; then
    echo "Creating archive" 1>&2
    tar -czf server.tar.gz org unit
else
    if [ 'nobuild' == "$1" ]; then
	$RUN
    else
	javac org/haldean/chopper/server/ServerHost.java -Xlint:deprecation && \
	    echo "Compiled" 1>&2 && \
	    $RUN
    fi
fi