#!/bin/bash

clean() {
    echo Clean old classfiles
    rm org/haldean/chopper/server/*.class
    echo Clean backup java files
    rm org/haldean/chopper/server/*.java\~
}

if [ 'clean' == "$1" ]; then
    clean
    exit
fi

clean

if [ 'pack' == "$1" ]; then
    echo Creating archive
    tar -czf server.tar.gz org unit
else
    javac -cp jars/trident.jar:jars/substance.jar:. \
	org/haldean/chopper/server/ServerHost.java && \
	echo Compiled && \
	java -cp jars/trident.jar:jars/substance.jar:. \
	org.haldean.chopper.server.ServerHost debug
fi